CREATE TABLE page_templates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL UNIQUE,
    source      VARCHAR(255)                            NOT NULL,
    category    VARCHAR(255)                            NOT NULL,
    config_json JSONB,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP,
    CONSTRAINT pk_page_templates PRIMARY KEY (id)
);

INSERT INTO page_templates(name, source, category, config_json) VALUES
('Kursy Walut USD', 'EXCHANGE_RATE', 'FINANCE', '{"currencyCode":"USD","lastCount":5}'),
('Kursy Walut EUR', 'EXCHANGE_RATE', 'FINANCE', '{"currencyCode":"EUR","lastCount":5}'),
('Tabela Ekstraklasa', 'SPORT_TABLE', 'SPORTS', '{"league":"ekstraklasa"}'),
('Wyniki Ekstraklasa', 'SPORT_MATCHES', 'SPORTS', '{"league":"ekstraklasa","week":48}'),
('Mecze Ekstraklasa', 'SPORT_MATCHES', 'SPORTS', '{"league":"ekstraklasa","week":49}'),
('Pogoda Wrocław', 'WEATHER', 'WEATHER', '{"city":"wroclaw"}')
